workspace:
  base: /go
  path: src/github.com/WellMafra/drone-demo

pipeline:
  build:
    image: instrumentisto/dep:0.4.1-alpine
    commands:
      - dep ensure
      - go test ./...
      - go build