version: '3'

services:
  drone-server:
    image: drone/drone:0.8.6

    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
      # adicionar /private no começo do path caso for MacOSX
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_ADMIN=WellMafra
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      # Descomente as linhas abaixo apenas se voce for usar banco de dados externo e não o padrão: sqlite
      #- DRONE_DATABASE_DRIVER=${DB_DRIVER}
      #- DRONE_DATABASE_DATASOURCE=${DB_DRIVER}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=disable

  drone-agent:
    image: drone/agent:0.8.6

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Comunica com docker para criar containers
      # adicionar /private no começo do path caso for MacOSX
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}
